-- Sincroniza order_transitions con el estado real de produccion.
-- Varias transiciones se fueron agregando en vivo (reembolsos desde servicios en
-- curso, pago que llega despues de vencer la reserva, cancelacion administrativa
-- en la entrega). Sin esto, una instalacion desde cero quedaba con la maquina de
-- estados incompleta. Idempotente: on conflict do nothing.

insert into order_transitions (from_state, to_state) values
  ('draft','quoted'),
  ('quoted','searching_provider'),
  ('searching_provider','provider_reserved'),
  ('searching_provider','awaiting_payment'),
  ('searching_provider','no_provider'),
  ('searching_provider','cancelled_by_client'),
  ('searching_provider','cancelled_by_admin'),
  ('provider_reserved','awaiting_payment'),
  ('provider_reserved','cancelled_by_client'),
  ('provider_reserved','cancelled_by_provider'),
  ('provider_reserved','cancelled_by_admin'),
  ('awaiting_payment','searching_provider'),
  ('awaiting_payment','payment_pending'),
  ('awaiting_payment','paid'),
  ('awaiting_payment','payment_expired'),
  ('awaiting_payment','cancelled_by_client'),
  ('awaiting_payment','cancelled_by_admin'),
  ('awaiting_payment','refund_pending'),
  ('awaiting_payment','refunded'),
  ('payment_pending','paid'),
  ('payment_pending','payment_expired'),
  ('payment_pending','cancelled_by_admin'),
  ('payment_pending','refund_pending'),
  ('payment_pending','refunded'),
  ('paid','provider_en_route'),
  ('paid','cancelled_by_provider'),
  ('paid','cancelled_by_admin'),
  ('paid','refund_pending'),
  ('paid','refunded'),
  ('provider_en_route','provider_arrived'),
  ('provider_en_route','cancelled_by_provider'),
  ('provider_en_route','cancelled_by_admin'),
  ('provider_en_route','refund_pending'),
  ('provider_en_route','refunded'),
  ('provider_arrived','vehicle_loaded'),
  ('provider_arrived','cancelled_by_admin'),
  ('provider_arrived','refund_pending'),
  ('provider_arrived','refunded'),
  ('vehicle_loaded','in_transit'),
  ('vehicle_loaded','cancelled_by_admin'),
  ('vehicle_loaded','refund_pending'),
  ('vehicle_loaded','refunded'),
  ('in_transit','completion_pending'),
  ('in_transit','cancelled_by_admin'),
  ('in_transit','refund_pending'),
  ('in_transit','refunded'),
  ('completion_pending','completed'),
  ('completion_pending','cancelled_by_admin'),
  ('completion_pending','refund_pending'),
  ('completion_pending','refunded'),
  ('completion_pending','disputed'),
  ('completed','disputed'),
  ('payment_expired','searching_provider'),
  ('payment_expired','paid'),
  ('cancelled_by_client','refund_pending'),
  ('cancelled_by_client','refunded'),
  ('cancelled_by_provider','refund_pending'),
  ('cancelled_by_provider','refunded'),
  ('cancelled_by_admin','refund_pending'),
  ('cancelled_by_admin','refunded'),
  ('refund_pending','cancelled_by_admin'),
  ('refund_pending','refunded'),
  ('disputed','cancelled_by_admin'),
  ('disputed','refund_pending'),
  ('disputed','refunded')
on conflict do nothing;
